name: Build & Test

on: 
  push:
env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOCKER_CLI_EXPERIMENTAL: enabled
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      # Fetch depth is crucial for gitversion
      with:
        fetch-depth: 0
    - name: Build the stack
      run: docker-compose up -d
